fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.1.0
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile.git
      ref: 1.0.3
    mongodb: git://github.com/puppetlabs/puppetlabs-mongodb.git
  symlinks:
    pulp: "#{source_dir}"
