name    'hawknewton-pulp'
version '0.1.0'
source 'https://github.com/hawknewton/puppet-pulp'
author 'hawknewton'
license 'Apache License, Version 2.0'
summary 'Setup pulp repository server and client'
description 'Setup and configure pulp repo (http://pulpproject.org) server, admin client, and client'
project_page 'https://github.com/hawknewton/puppet-pulp'
dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
dependency 'puppetlabs/inifile', '>=1.0.0 <2.0.0'
